# Generated by Django 6.0.1 on 2026-01-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stocklog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklog',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
